%
% Copyright (c) 2013 Michael Shafae
% All rights reserved.
%
% $Id: msnameplate.cls 5915 2015-08-31 06:31:06Z mshafae $
%
% A latex class for making an office hours sign.
%

\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{msofficehours}[2013/03/07 M.S. Office Hours Class]

\LoadClassWithOptions{article}

%\RequirePackage{mscommon}
%\RequirePackage{xfrac}
\RequirePackage{setspace}
%\RequirePackage{listing}
%\RequirePackage{listings}
%\RequirePackage{multirow}
%\RequirePackage[xetex]{hyperref}
%\RequirePackage{hyperxmp}
%\RequirePackage{amsmath}
%\RequirePackage{fancyhdr}


\AtBeginDocument{\singlespacing}
%\AtBeginDocument{\maketitle}
\AtBeginDocument{\pagestyle{empty}}
%\AtBeginDocument{\syllabusheader}
%\AtBeginDocument{\syllabusfooter}
